services:
  nextjs_app:
    build: .
    container_name: vanilla_nextjs_app
    environment:
      - KEYCLOAK_ISSUER=http://host.docker.internal:8080/realms/test-realm
      - NEXTAUTH_URL=http://host.docker.internal:3000
      - NEXTAUTH_SECRET=secret
      - HOSTNAME=0.0.0.0
      - KEYCLOAK_CLIENT_ID=test-client
      - KEYCLOAK_CLIENT_SECRET=ZnVdxKDCe2lRcJcPoXOZNWqh1UxuUNUV
    ports: 
      - "3000:3000"
    volumes:
      - ./:/app/
    networks:
      - my_network

  keycloak_app:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    command: start-dev --import-realm
    volumes:
      - ../keycloak/data/import:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: host.docker.internal
    networks:
      - my_network
    
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network


volumes:
  keycloak_postgres_data:

networks:
  my_network:
    driver: bridge